### ISSUE TITLE
MD automatic generator does not support accents

### ISSUE THREAD

**Issue by gregory-vorbe** [convertigo/convertigo#652] opened 2022-10-03 09:36 UTC
**Convertigo EMS Studio 8.1.0_beta (build 14338-develop-8.1.0-beta)**

![image](https://user-images.githubusercontent.com/1685373/193545390-8e464a02-9fef-44e6-988c-d00b96480f86.png)

Created project in Studio 7.9.8. Files are UTF-8 encoded.
Imported project in 8.1.0 to generate md file.
French accents are replaced by <?>
Files are still in UTF-8 in Studio 8.1.0

**Comment by nathalie-lammelin** [comment] 2022-10-03 10:17
**Not reproduced** with a fresh 8.1.0 project.
`lib_extra_actions_c8oforms` not found on github: could you join the project for reproduction purpose ?

**Comment by nathalie-lammelin** [comment] 2022-10-03 10:33
> **Not reproduced** with a fresh 8.1.0 project. `lib_extra_actions_c8oforms` not found on github: could you join the project for reproduction purpose ?
Could you join the 7.8.9 **original** project ?

**Comment by gregory-vorbe** [comment] 2022-10-03 10:51
Here is the 7.9.8 project. It already contains de fixed .md files, but can probably be re-generated in 8.1.0:

[lib_extra_actions_c8oforms.zip](https://github.com/convertigo/convertigo/files/9696836/lib_extra_actions_c8oforms.zip)

**Comment by nathalie-lammelin** [comment] 2022-10-03 11:51
Not reproduced either.

**Comment by nathalie-lammelin** [comment] 2022-10-03 12:11
Closed as invalid. Anyway the file can be fixed.

**Comment by gregory-vorbe** [comment] 2022-10-03 12:29
Here is the project without de .md files:
[lib_extra_actions_c8oforms.zip](https://github.com/convertigo/convertigo/files/9697442/lib_extra_actions_c8oforms.zip)
I imported the project in Studio 8.1.0 and generated the md files from scratch:
![image](https://user-images.githubusercontent.com/1685373/193576791-a3498f81-fafd-40a7-8f47-c756bfc13c8e.png)

**Comment by nathalie-lammelin** [comment] 2022-10-03 13:46
The issue is related with an environnement trouble. Reopened to investigate.
There's a difference between the **Built Studio** and the **Dev Studio**.

- the **Built Sudio** comes with a workspace `Text file encoding`
  - unselected `default encoding` set to `windows-1252` 
  - selected `other` set to `UTF-8`
- the **Dev Sudio** comes with a workspace `Text file encoding`
  - unselected `default encoding` set to `UTF-8` 
  - selected `other` set to `UTF-8`

**Closed** 2022-10-03 14:04 UTC
Labels: bug

**Comment by gregory-vorbe** [comment] 2022-10-03 15:53
OK in **Convertigo EMS Studio 8.1.0_beta (build 14356-develop-8.1.0-beta)**
