### ISSUE TITLE
Alert on mobile with flashupdate

### ISSUE THREAD

**Issue by do91** [convertigo/convertigo#82] opened 2019-03-12 14:00 UTC
This happens very often during the flashupdate, an alert, several times ok and after that looks good.
Convertigo version 7.6.0_beta (build 02206-develop-7.6.0-beta)
![20190312_143609](https://user-images.githubusercontent.com/39701177/54205896-87e37900-44d7-11e9-93f2-5df2d5bb1ace.jpg)

**Comment by nicolas-albert** [comment] 2019-05-09 12:47
Handle network error and tell to restart the app.

**Comment by opicciotto** [comment] 2019-06-06 15:32
This is an issue cause most probably by a very unstable WIFI network. We cannot reproduce.. So we close it for now.

**Closed** 2019-06-06 15:32 UTC
Labels: bug, wontfix
